POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer {{$processEnv TOKEN}}

{
    "author": "Teite Sampson",
    "url": "https://github.com/j2sleek",
    "title": "Testing the user extractor middleware"
}